title: Dat Hoang's Blog
description: Học Machine Learning bằng JavaScript

url: https://dathoangblog.com
baseurl: "/dathoangnd.github.io"
paginate_path: "blog/page:num/"
permalink: /:year/:month/:title.html

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 100

navigation:
  - title: Nhật ký
    url: /
  - title: Machine Learning
    url: /machine-learning
  - title: Dự án
    url: /projects
  - title: Liên hệ
    url: /contact
  - title: Về tôi
    url: /about

social:
  github: dathoangnd
  facebook: dathoangnd
  email: dathoangnd@gmail.com

google_analytics:
